baseURL = "https://<your-namespace>.gitlab.io/<project-path>/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"
paginate = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
